default_platform(:ios)

platform :ios do

  error do |lane, exception, options|
    UI.error exception.message
  end

  lane :build do
    timestamp = Time.now.strftime("%Y%m%d%H%M%S")
    package = load_json(json_path: '../package.json')
    version_number = package['version']
    build_number = '1'
    build_output_directory = './fastlane/build'
    build_output_filename = "#{package['version']}-#{timestamp}.ipa"
    yarn(command: 'install --frozen-lockfile --network-concurrency=32 --network-timeout=1000000 --cache-folder $TMPDIR/.ycacheproduction', package_path: '../package.json')
    sh("./fix_rn.sh")
    cocoapods({
      clean_install: true,
      deployment: false,
    })
    sh("./fix_pods.sh")
    gym({
      clean: true,
      export_method: 'app-store',
      configuration: 'Release',
      output_directory: build_output_directory,
      output_name: build_output_filename,
      skip_codesigning: true,
      skip_archive: true,
    })
  end

end
